# Generated by Django 4.2.5 on 2023-09-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectView',
            fields=[
                ('directViewID', models.AutoField(primary_key=True, serialize=False)),
                ('problemStatement', models.CharField(max_length=255)),
                ('abstractData', models.TextField()),
                ('blockDiagram', models.TextField()),
                ('solution', models.TextField()),
                ('implementation', models.TextField()),
                ('conclusion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('directViews', models.ManyToManyField(to='plg.directview')),
            ],
        ),
    ]
